# Facilitator Authentication Configuration
# This file contains the credentials for facilitators who can create and manage workshops

facilitators:
  - email: "facilitator123@email.com"
    password: "facilitator123"  # In production, use environment variables
    name: "Databricks Facilitator"
    description: "Primary workshop facilitator"
  
  # Add more facilitators as needed
  # - email: "another.facilitator@databricks.com"
  #   password: "another_password"
  #   name: "Another Facilitator"
  #   description: "Secondary workshop facilitator"

# Security settings
security:
  # Default password for new users (SMEs and participants)
  # Users will be prompted to change this on first login
  default_user_password: "changeme123"
  
  # Password requirements
  password_requirements:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: false
  
  # Session settings
  session:
    token_expiry_hours: 24
    refresh_token_expiry_days: 7
